import * as Prism from 'prismjs'
import 'prismjs/components/prism-docker.min.js'
import 'prismjs/components/prism-elm.min.js'
import 'prismjs/components/prism-haskell.min.js'
import 'prismjs/components/prism-json.min.js'
import 'prismjs/components/prism-rust.min.js'
import 'prismjs/components/prism-typescript.min.js'
import 'prismjs/components/prism-yaml.min.js'
import 'prismjs/themes/prism-tomorrow.css'
export { default as wrapRootElement } from './redux-wrapper'
